from decouple import config

DEFAULT_ORDER_STATUS = "На рассмотрении"
DEFAULT_CURRENCY = "₽"

SUPABASE_URL = config("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = config("SUPABASE_SERVICE_ROLE_KEY")
EVOTOR_TOKEN = config("EVOTOR_TOKEN")
EVOTOR_STORE_UUID = config("EVOTOR_STORE_UUID")